### ISSUE TITLE
Verification method type definition missing

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#56] opened 2024-08-25 22:20 UTC
https://www.w3.org/TR/2024/WD-controller-document-20240817/#verification-methods
The "type" definition says "The value of the type property MUST be a string that references exactly one verification method type." but there is no link to the definition of verification method types.  Instead, the verification method link goes to a place that doesn't define the types.

**Comment by dlongley** [comment] 2024-08-28 15:57
This might be a duplicate of #58.

**Comment by selfissued** [comment] 2024-08-29 00:12
I agree that this is ready for a PR.

**Comment by iherman** [comment] 2024-09-01 07:10
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-28-vcwg#section4-8) on 2024-08-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.8. Verification method type definition missing (issue controller-document#56)

_See github issue [controller-document#56](https://github.com/w3c/controller-document/issues/56)._




**Michael Jones:** this is one of a few of such issues, has to do with - is there an actionable way for a naive reader to find the thing.  

**Manu Sporny:** yeah, I can raise a PR to do that.  

**Michael Jones:** thank you.  

**Brent Zundel:** ok, one more.  

</details>

**Comment by msporny** [comment] 2024-09-08 22:47
PR #78 has been merged, closing.

**Closed by msporny** 2024-09-08 22:47 UTC
Labels: pr exists, editorial
