### ISSUE TITLE
What is the role of the subject when the controller property is present?

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/controller-document#33] opened 2024-06-19 15:41 UTC
It is clear that if there is no controller property then the subject has full control of the document. But what is the case when the controller property is added? Does the subject continue to have all powers when the controller property is added, or does the controller property override the subject's control?

**Comment by dlongley** [comment] 2024-06-19 16:42
The controller property overrides the subject's control. +1 to document this.

Note: The subject could be listed as one of the controllers to allow multiple controllers including the subject.

**Comment by jandrieu** [comment] 2024-07-31 15:35
I'm not seeing in the spec where it says that subjects have any control over anything.

**Comment by David-Chadwick** [comment] 2024-07-31 15:42
@jandrieu If there is no controller property then the subject has full control of the document. So it should be explicit that if the controller property is added then all control is removed from the subject (unless they are explicitly named in the controller property)

**Comment by jandrieu** [comment] 2024-07-31 17:42
Unfortunately, the subject has no specific control over the document. Is there language in this spec (or DID core) that suggests otherwise?

I think this is essentially an echo of the discussion about holder != subject. 

The subject referred to by a DID may or may not even be aware of the DID.

Perhaps even more confusing in this whole problem, the "controller" property DOES not indicate the Controller role. I know it seems like it should or does, but its a subtly different function.

The controller property says "for this DID Document, include the verification relationships from this/these OTHER DID document(s) as if they were defined herein"

It is a handy way to link DIDs together so that cryptographic material in a base DID propagates (in practice) for use by other DIDs (who include the base DID in their controller property).

This largely has the effect, with many VDRs, that the controller as listed in the controller property is, functionally, the Controller of updates to the DID document. Maybe that should be a "SHOULD" to encourage method creators to support that pattern.

However, some VDRs cannot export the a controller property for the Controller, because they cannot reduce the actual Controller to just a DID. For example, using `did:btcr`, the control mechanism in the VDR is a bitcoin script, which is not yet reducible to a DID, except for the self-reference pattern described in the next paragraph.

In my experience, the controller property is mostly used to assert that no other DID documents are needed to resolve the cryptographic mechanisms used to verify interactions with the DID in question. That is, the controller property is often just the DID of that DID document, it matches the "id" property of the root JSON object. No external controller defined at all.

Maybe the right way to address this is to require that a DID document needs at least one controller, which, if there are no external controllers, MUST be the DID of the document. I'm not too sure about this suggestion, but we do need some language that helps clarify for people the difference between actual, functional control over the record in the VDR and the "controller" property which is used for including verification relationships from external DID documents.

**Comment by David-Chadwick** [comment] 2024-07-31 18:56
Not forgetting did:jwk where there is no controller document!

**Comment by selfissued** [comment] 2024-08-01 06:27
@jandrieu asks some good questions that possibly point out unspecified but assumed behaviors.  Where appropriate, we should make these behaviors explicit.

BTW, what is a VDR?  The term isn't present in either of https://w3c.github.io/did-core/ or https://w3c.github.io/controller-document/ .

**Comment by David-Chadwick** [comment] 2024-08-01 08:18
The VDR is a conceptual repository of verifiable data. But little of it is standardised. The controller document is a standardised part of the VDR. So with this in mind it should be authoritative unless an implementation has other non-standardised means of providing competing information.

**Comment by TallTed** [comment] 2024-08-01 17:30
VDR is an acronym of art, standing for Verifiable Data Repository, in our use. The acronym is not so overloaded as many, but [still not unique](https://acronymfinder.com/VDR.html) to us.

"Verifiable Data Repository" should indeed be added to a definition list, for reference from wherever we might use it, and "VDR" should never be used without a nearby expansion to "Verifiable Data Repository" (with citation of the definition).

That said, I'm not sure that either the [DID Core](https://w3c.github.io/did-core/) or the [Controller Document](https://w3c.github.io/controller-document/) spec is the right place for an authoritative definition, but I think either could include an operational definition for this area of use.

**Comment by selfissued** [comment] 2024-08-02 22:07
@David-Chadwick can you propose a sentence making explicit what you point out is currently implicit?  Thanks.

**Comment by iherman** [comment] 2024-08-04 14:22
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-1) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. What is the role of the subject when the controller property is present? (issue controller-document#33)

_See github issue [controller-document#33](https://github.com/w3c/controller-document/issues/33)._




**Brent Zundel:** first issue: 33. What is the role of the subject when the controller property is present.  
… first question: DavidC, was dlongley's suggestion adequate, would this suggestion resolve your concern?  

**David Chadwick:** Yes, this knowledge needs to be explicit in the spec.  

**Manu Sporny:** I can write this PR.  

</details>

**Comment by iherman** [comment] 2024-08-04 14:22
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-10) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.10. What is the role of the subject when the controller property is present? (issue controller-document#33)

_See github issue [controller-document#33](https://github.com/w3c/controller-document/issues/33)._




**Joe Andrieu:** David had mentioned that if we don't have controller, does the subject get control back? But the subject doesn't have control, no mechanism for that, may have answered that incorrectly.  

**David Chadwick:** controller property is optional, if it's missing does the subject have control over setting Controller Document.  

**Joe Andrieu:** subject may not be controller.  

**David Chadwick:** Something needs to be said, if no controller property who has control?  

**Gabe Cohen:** It should be explicit who the controller is, might not be subject even if no controller present, would like more detail on "depends on VDR", would like to always see controller present.  

**Manu Sporny:** agree with Joe that it depends on VDR, don't think that saying that controller must always exist is a good idea, some use cases where that doesn't make sense e.g. write only things.  
… language we could add is to say that if controller not set, controller is determined by policy of the VDR.  

**Brent Zundel:** my view is that if there is a controller that is explicit then that entity is the controller, in absence of that, the controller by default would be the holder of the credential.  
… if the holder is the subject or not is moot.  

**Manu Sporny:** ok for controller to be unknown, for use cases there it's up to the VDR.  
… -1 for saying you must specify controller in every controller document.  
… saying you SHOULD is a weaker form of that mistake.  
… trying to figure out when it matters to know who the controller is, typically only for updating, if not specified, the answer is "I don't know".  
… It's been suggested that the subject is in control of it but that's not always true either.  
… Brent, you mixed VCs in with it, and I think that's fine in a VC interpretation, but the controller document is not really playing a part in that question in that way.  
… all that to say that it's OK for the controller to be unknown.  
… SHOULD is a little dicey here.  

**Dave Longley:** my main point is that whatever we do here should continue to allow layering DID documents on top of controller document spec.  

**Brent Zundel:** no longer have agreement on path forward on #33 - any suggestions? what action if any should be taken?  

> *Gabe Cohen:* +1 to that we need to know who's flying the plane.

**Manu Sporny:** the only thing I can think of to reach consensus is to say it's up to the VDR to say who the controller is if it's not specified in the document.  

**Brent Zundel:** that's the path we have, we will say as much as we can, ok that sometimes you might not know who is flying the plane.  
… We talked about everything we wanted to talk about.  

**David Chadwick:** re: manu, if we say the VDR says who is in control if the controller document doesn't say that's fine, but we need to say that if controller is present it overrides VDR.  

**Joe Andrieu:** We can't override VDR.  

> *Dave Longley:* the VDR allowed that controller property to exist.

> *Dave Longley:* it's not an "override".

**David Chadwick:** this yields a contradiction when VDR and document say different things.  

**Manu Sporny:** controller document establishes what all VDRs must do.  
… the rules for VDRs. I agree, we put ourselves in weird position if we say the controller field is entirely dependent on VDR.  
… I don't know if it's an override, as dlongley says.  

**Joe Andrieu:** we need more time kicking this around, there are subtleties that need discussion.  

**Brent Zundel:** thanks all, looking forward to seeing PRs.  

---

</details>

**Comment by jandrieu** [comment] 2024-08-06 17:49
> Not forgetting `did:jwk` where there is no controller document!

I'd make the case that `did:jwk` resolves to DID Documents, which is the controller document for that `did:jwk` DIDs.

Perhaps what's more interesting is that `did:jwk`, like `did:key`, puts the VDR directly in the did-method-specific identifier. No external resources required.

But there is still a VDR, which, to @selfissued's point, we should figure out how/where we talk about it. And maybe needs a different name, e.g., controller repository or controller document store.

This probably goes in the controller document spec, as the VDR is wherever the data for the controller document is stored. Not sure where in the doc, but it's kind of hard, IMO, to talk about controller docs without talking about how to get them, which for DIDs is from the VDR per the DID method of each DID. 

Not sure how the non-DID folks would map that language to their mental model.

**Comment by TallTed** [comment] 2024-08-07 15:22
Relevant to this issue...

I just tripped over [B.9 The relationship between DID controllers and DID subjects](https://www.w3.org/TR/did-core/#the-relationship-between-did-controllers-and-did-subjects) in the DID Core spec.

I also note the definition of DID controller:
> An entity that has the capability to make changes to a [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents). A [DID](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers) might have more than one DID controller. The DID controller(s) can be denoted by the optional controller property at the top level of the [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents). Note that a DID controller might be the [DID subject](https://www.w3.org/TR/did-core/#dfn-did-subjects).

and of DID subject:
> The entity identified by a [DID](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers) and described by a [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents). Anything can be a DID subject: person, group, organization, physical thing, digital thing, logical thing, etc.

Also see [5.1.1 DID Subject](https://www.w3.org/TR/did-core/#did-subject), [5.1.2 DID Controller](https://www.w3.org/TR/did-core/#did-controller).

@David-Chadwick — None of this seems to support your assertion, that "if there is no controller property then the subject has full control of the document". Further, it suggests that "when the controller property is added", "the controller property [would] override the subject's control" if the subject _had_ any control prior to addition of controller prpperty, which appears not to be the case.

**Comment by David-Chadwick** [comment] 2024-08-08 20:52
This is how my logic went that caused this issue to be raised. The following text is copied verbatim from the controller draft:

1. The identifier for a particular subject is expressed using the id property in the controller document. The id property only denotes the identifier of the subject when it is present in the topmost map of the controller document. (Clause 2.1.1)
2. A controller is an entity that is authorized to make changes to a controller document.(Clause 2.1.2)
3. The controller property is OPTIONAL.(Clause 2.1.2)
4. If the controller property is not present, the value expressed by the id property MUST be treated as if it were also set as the value of the controller property.(Clause 2.1.2)

Conclusion. The subject is the controller if the controller property is not present and the id property is present in the topmost map of the controller document.

**Comment by msporny** [comment] 2024-08-17 14:34
PR #42 has been raised to address this issue. This issue will be closed once PR #42 has been merged.

**Comment by jandrieu** [comment] 2024-08-18 16:31
> Conclusion. The subject is the controller if the controller property is not present and the id property is present in the topmost map of the controller document.

The subject of the DID is *identified by* the DID, they do not have any control over it or its associated DID document.

The unfortunate flaw in the argument is because the "controller" property has nothing to do with the "Controller" role.

The Controller is a role defined by the fact of controlling the VDR's authoritative representation of a DID.

The "controller" property specifies how to retrieve additional verification details from other controller documents. It says NOTHING about the Controller, which is defined by the VDR.

To wit, the Controller of a did:web DID is whoever can edit the content of that web endpoint. There is no innate relationship between the subject of such a DID and the person or persons who have the ability and/or authority to update the document on the server.

The heart of the confusion is the unfortunate overloading of the term "controller" as a property with "Controller" as a role.

Controller != "controller"

**Comment by David-Chadwick** [comment] 2024-08-19 09:57
> The unfortunate flaw in the argument is because the "controller" property has nothing to do with the "Controller" role.

How bizarre is that? 

Further, the Controller document is part of the VDR. It is a standardised part of the VDR, it is not separate from the VDR.

**Comment by TallTed** [comment] 2024-08-20 17:42
> The heart of the confusion is the unfortunate overloading of the term "controller" as a property with "Controller" as a role.

I daresay we should call that a "bug". We might have to document this overloading as a fact of the past, but I hope a revision (even if it forces another round of CR) that removes that overloading might find consensus for the future.

**Comment by dlongley** [comment] 2024-08-20 18:36
@TallTed,

> I daresay we should call that a "bug". We might have to document this overloading as a fact of the past, but I hope a revision (even if it forces another round of CR) that removes that overloading might find consensus for the future.

I don't think there's necessary (precise) agreement on Joe's take. I have a different perspective, which is that "controller" *is* for "Controller", it's just that we weren't really rigid, for example, with requiring VDR's to honor the use of verification methods for performing updates to the DID document.

The "controller" property is for informing applications about which entities control the verification methods in the DID document (and which entities may substitute/use their own) -- which is indirectly about *what can be done with those verification methods*. For example, if you say, in some other system that leverages DIDs, that DID `X` controls resource `Y`, and that the resource can be manipulated using verification methods, then the expectation is that the verification methods in the DID document (or those of any `controller` of the DID document) could be used to do this -- provided that they are expressed using an acceptable verification relationship.

Notably, such applications only work at the DID document layer and should not break abstractions to get at DID-method/DID-resolver/VDR-specific details, and it's *possible* for a VDR to not honor the use of those verification methods in update processes of the DID document itself.

However, I think it's an anti-pattern for a VDR to specifically prohibit the use of the verification methods in a DID document (or those from an entity identified in its `controller` property) from being used in a process (in one way or another) that updates the DID document. Not only do I think this shouldn't be a "special case", the idea that a DID document cannot express its controller(s) (I do mean "Controller" role here) or that the verification methods therein (or of a listed `controller`) are specifically prohibited from being used to update that same DID document is, in my view, antithetical to DIDs.

While a VDR is always the root of control for all the DID documents that it "provides"/"stores"/"serves", the VDR (either itself or in conjunction with the DID method's design somehow) must consent to allowing the expression of `controller` (or any other property) in a DID document. If it does not want to signal to applications the expectation that the entities identified in that field would be able update the DID document (if given the right feature to do so), it should just prevent such expression (one way or another) of that field. If a VDR just doesn't (yet?) have the capability to enable updates that the identified controllers (expressed via `controller`) would be sanctioned to participate in (somehow), I think that's not ideal, but ok.

**Comment by msporny** [comment] 2024-09-20 12:50
PR #42 has failed to achieve consensus, the issue is being tracked in https://github.com/w3c/controller-document/issues/75 as well.

**Comment by msporny** [comment] 2024-09-22 16:18
In order to make progress at W3C TPAC, I am suggesting that this issue can be marked as "at risk" and resolved during the Candidate Recommendation phase. The VCWG will discuss this issue to see if the "during CR" determination is correct.

**Comment by iherman** [comment] 2024-09-29 12:48
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-09-27-vcwg#section3-8) on 2024-09-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.8. What is the role of the subject when the controller property is present? (issue controller-document#33)

_See github issue [controller-document#33](https://github.com/w3c/controller-document/issues/33)._




**Manu Sporny:** that one is during CR as well, I believe JoeAndrieu has language for that that will be PR'd, in theory we can address that, one option is to mark it at risk and change the defn during CR, which is appropriate, or we can handled it now.  

**Ivan Herman:** I will repeat what I said on the DID working group, the whole discussion of controllers that took place on Tuesday at the DID WG should in fact take place here.  
… the DID spec only refers to the controller document.  
… I must admit I was a bit lost with the discussion so cannot go into details, but there are some issues from the DID WG that should be transferred here.  

**Manu Sporny:** that's only pre CR if JoeAndrieu believes there is some kind of huge normative change that we are going to make that is going to change... I don't know why we couldn't deal with it in CR if we mark it "at risk". I don't think it would change an implementation, whatever we end up doing.  

**Ivan Herman:** It's difficult to say that, you put a feature at risk, not the definition of a feature.  

**Manu Sporny:** then it's not at risk, it's just going to maybe change.  

**Ivan Herman:** if the defn now is acceptable for everyone, if JoeAndrieu gets to the point that something need to be fundamentally reengineered, that needs to happen now.  

**Joe Andrieu:** not sure why putting it "at risk" is not good enough, we have the issue where dlongley, selfissued, and I went back and forth about what you prove and how this document lets you evaluate proofs created by the controller, that is an editorial cleaning up. What is at risk is the property "controller", and what text is in the spec right now nobody supports. The language will probably trend towards "should, and if you do, you must".  
… That feels like cleaning up that is close enough to consensus that we will get there.  

**Ivan Herman:** As a reminder, the "at risk" thing is used when you go to CR with a property but you are not sure it will be implemented. It's not questioning the definition itself, it is whether it is implemented or not, you reserve the right to ignore that term. What you are discussing is not that, it is the definition of the controller. You are not removing controller altogether.  

**Joe Andrieu:** removing controller is on the table.  

**Ivan Herman:** In CR you can remove it without further ado if it is not implemented. The CR needs to prove that the spec can be implemented. At risk shows that something can or may not be implemented. Leaning too much on at risk in this discussion.  

**Joe Andrieu:** You have convinced me Ivan, I will get something on this this week, will get us to CR hopefully soon.  
… This brings in issue 75.  

**Ivan Herman:** need to liaise this back to DID, this is where the two WGs are related.  

**Brent Zundel:** any other issues that the editors feel the group should discuss?  

**Manu Sporny:** the name of the document.  

**Ivan Herman:** no >:(.  

</details>

**Comment by iherman** [comment] 2024-10-10 04:06
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-10-09-vcwg#section3-1) on 2024-10-09

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. What is the role of the subject when the controller property is present? (issue controller-document#33)

_See github issue [controller-document#33](https://github.com/w3c/controller-document/issues/33)._




**Manu Sporny:** switching to controller document, the first issue, JoeAndrieu, is waiting on you for PR text, this is issue 33 and also issue 75.  

_See github issue [controller-document#75](https://github.com/w3c/controller-document/issues/75)._




**Joe Andrieu:** I have 90% of a PR for one of them, which is the language around that a controller document lets you verify proofs. That was a straightforward change, the other is on my queue and I will have something by next week, that has language defining the controller property, which is a CR issue.  

**Manu Sporny:** moving through the other issues, there were a number of these that we briefly discussed during W3C TPAC, we marked them as discussed or editorial, we have not had any pushback on the editorial nature of most of them, so we are going to address those during the CR phase.  

</details>

**Comment by msporny** [comment] 2024-10-16 15:44
PR #102 has been raised to address this issue. This issue will be closed once PR #102 has been merged.

**Comment by David-Chadwick** [comment] 2024-10-21 19:52
The current proposed text in PR #102 does not address this issue. It does not say anything about the subject being or not being the controller

**Comment by msporny** [comment] 2024-10-28 01:34
> It does not say anything about the subject being or not being the controller

@jandrieu has volunteered to write some text around that. As a result, I've removed the "pr exists" and "discuss" labels. We think we have some conceptual text agreed to, the next step is for @jandrieu to raise a PR for the group to review.

**Comment by msporny** [comment] 2024-11-16 17:46
PR #116 has been raised to address this issue. This issue will be closed once PR #116 has been merged.

**Comment by msporny** [comment] 2024-11-23 18:05
PR #116 has been merged, closing.

**Closed by msporny** 2024-11-23 18:05 UTC
Labels: pr exists, normative
