### ISSUE TITLE
RFC 2119 key word NOT RECOMMENDED is missing

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#47] opened 2024-08-25 22:01 UTC
Per https://www.rfc-editor.org/rfc/rfc8174#section-2, the RFC 2119 text that should be included is:

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here.

The odd thing is that none of the RFC 2119 text appears in the source for the document.  It's being magically imported from elsewhere.  If someone can point me to that elsewhere, I'll create a PR updating the text per RFC 8174.

**Comment by iherman** [comment] 2024-08-26 06:21
This is the boilerplate text that is added to the content by our publication system and is therefore identical to all our documents. Removing that, or part of this, would require fiddling around with respec, or add some javascript to artificially modify the generated content. I do not think we should do that.

You can raise an issue in respec to update the relevant section. In the meantime, we should indeed avoid using "NOT RECOMMENDED".

**Comment by msporny** [comment] 2024-08-26 19:06
Moreover, ReSpec automatically builds that list of keywords based on the actual keywords used in the specification. All W3C specs that use ReSpec do this, we shouldn't do anything differently.

**Comment by msporny** [comment] 2024-08-26 21:33
> Where do I file the ReSpec issue?

You don't have to, the issue was raised and discussed over a decade ago:

https://github.com/speced/respec/issues/345

BCP 14 was taken into account in ReSpec more recently when this fix went in: https://github.com/speced/respec/pull/2346

You'd be raising an issue that would be marked as a duplicate of https://github.com/speced/respec/issues/345.

**Comment by TallTed** [comment] 2024-08-29 19:03
> Moreover, ReSpec automatically builds that list of keywords based on the actual keywords used in the specification

In other words, if someone puts `NOT RECOMMENDED` into the document (presumably, using the special RFC2119 markup), the RFC2119/BCP14 disclaimer will then include `NOT RECOMMENDED`; i.e., it will not be missing once it has meaning within the document. If I correctly understand how the tooling works, the PR-Preview would show this change upon creation of such a PR, which creation I encourage, in order to speedily close this issue.

**Comment by msporny** [comment] 2024-09-11 13:26
> > Moreover, ReSpec automatically builds that list of keywords based on the actual keywords used in the specification
> 
> If I correctly understand how the tooling works, the PR-Preview would show this change upon creation of such a PR, which creation I encourage, in order to speedily close this issue.

This has been done in PR #95, and you can see the expected behavior in this diff:

https://pr-preview.s3.amazonaws.com/w3c/controller-document/95/1709c9e...728b243.html#conformance

**Comment by msporny** [comment] 2024-09-16 14:53
The group discussed this last week and consensus was to use the current approach in the specification. Closing.

**Closed by msporny** 2024-09-16 14:53 UTC
Labels: pending close

**Comment by TallTed** [comment] 2024-09-16 15:04
(I posted this comment elsewhere, but it is in reply to this issue, so belongs here.)

It seems worth noting that [RFC2119/BCP14](https://datatracker.ietf.org/doc/html/rfc2119) says *in its **abstract***, 
```
   Authors who follow these guidelines
   should incorporate this phrase near the beginning of their document:

      The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
      NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
      "OPTIONAL" in this document are to be interpreted as described in
      [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119).
```

(1) Abstracts are not generally normative, even in IETF documents. Rather, they provide an _informative_ summary of the document that contains them.

(2) Even if taken as normative, the guidance is a SHOULD, not a MUST, and the incorporated "phrase" (it should be called a sentence, perhaps even a paragraph) talks about how the listed key words are meant to be interpreted when they occur _in the document containing the "phrase"_ — so it makes little sense to list key words that do not occur in that document.

In sum: I believe ReSpec's output is in compliance with RFC2119/BCP14.
