### ISSUE TITLE
Contexts and Vocabularies inconsistencies

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#10] opened 2024-05-05 01:43 UTC
The Contexts and Vocabularies sections in VC Data Integrity and the Controller Document are inconsistent and there is no Contexts and Vocabularies section in VC JOSE COSE at all.  We need to determine what this content should be, where it should be, and where it's not needed.

Can we, for instance, simply delete it from the Controller Document spec like was done in VC JOSE COSE?  Or should it be deleted from VC DATA INTEGRITY when it's updated to reference the Controller document spec?

**Comment by iherman** [comment] 2024-05-21 11:45
This is relevant for this issue, as well as #15 and #18.

In my view, there are two approaches:

1. We separate the terms defined in the controller document into a separate vocabulary. In that case #18 becomes, partially, moot, because the terms should be removed from the current DI vocabulary, and the vocabulary section in this spec should be rewritten accordingly. Also, a completely new vocabulary file should be created alongside this document, just like we did for the bitstring status list.
2.  While the formal specification of the terms (e.g., "authentication") _are_ (eventually) part of the controller document, the formal vocabulary (its URL, etc.) remains unchanged, except for the references of the term definition (per #18). Because that vocabulary (and related context) is much larger than what the controller document defined, it makes sense to remove this section from the controller spec and leave the DI spec in charge.

From a purely editorial/consistency point of view, my preference would be (1). However, those terms are already in use out there (including for DID) using the same base URL as the core DI vocabulary, I believe our only _real_ option is to go with (2).

**Comment by iherman** [comment] 2024-06-26 16:21
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-26-vcwg#section3-4) on 2024-06-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Contexts and Vocabularies inconsistencies (issue controller-document#10)

_See github issue [controller-document#10](https://github.com/w3c/controller-document/issues/10)._




**Manu Sporny:** we need to make the content and vocabularies consistent.  
… we already have a security vocabulary so dont need a new controller doc vocabulary.  

**Ivan Herman:** if you go to the vocabulary document we refer to one or our specs for the definition of the term.  
… so any references to one of our security specs should refer to controller doc instead.  

> *Dave Longley:* +1 to ivan's plan, unless we bump into some issue.

> *Manu Sporny:* Yes, +1 agree with Ivan on the path forward.

> *Manu Sporny:* We won't be updating the security context.

> *Manu Sporny:* (IMHO).

**Dmitri Zagidulin:** manu mentioned updating security vocabulary. This does not require update to security context as well.  

**Ivan Herman:** keeping security vocabulary URLs as now means less changes. We only need to point to controller doc for the definition of terms. The context document remains unchanged.  

> *Manu Sporny:* Yes, +1 to what ivan said, agreed.

</details>

**Comment by selfissued** [comment] 2024-08-02 21:31
Let's talk about this on the next WG call and try to determine a resolution.

**Comment by iherman** [comment] 2024-08-04 09:34
This issue has been overcome by events and it is now moot. The DI vocabulary has been updated, referring to the term definition in the Controller Document (see, for example, [`assertionMethod`](https://w3c.github.io/vc-data-integrity/vocab/security/vocabulary.html#assertionMethod)). This means alternative (2) above was put into a PR and subsequently merged.

Propose closing.

**Comment by iherman** [comment] 2024-08-04 09:40
> Can we, for instance, simply delete it from the Controller Document spec like was done in VC JOSE COSE? 

I do not think so. The controller document must be relevant for the DID spec as well, which does use the JSON-LD contexts.

> Or should it be deleted from VC DATA INTEGRITY when it's updated to reference the Controller document spec?

That may be more consistent with the DID spec point of view.

**Comment by iherman** [comment] 2024-08-04 14:22
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-4) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. Contexts and Vocabularies inconsistencies (issue controller-document#10)

_See github issue [controller-document#10](https://github.com/w3c/controller-document/issues/10)._




**Brent Zundel:** next issue #10, currently assigned to ivan.  
… Ivan presented a plan, just implementing the plan that was proposed last time we talked.  
… Ivan has said he will do it, it will get done.  

**Joe Andrieu:** I had to review the issue to try and understand if my interpretation was right or not, I'm concerned people might be imagining that subject has some power, there might be a mismatch between David's actual concern and that other issue.  

**Brent Zundel:** Please indicate that in the comments, we can keep going and loop back if there is time.  

</details>

**Comment by dlongley** [comment] 2024-08-14 15:58
This: https://w3c.github.io/vc-data-integrity/vocab/security/vocabulary.html#assertionMethod

Now has a link in it pointing to: https://www.w3.org/TR/controller-document/#defn-assertionmethod

**Comment by iherman** [comment] 2024-08-14 16:12
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-14-vcwg#section4-9) on 2024-08-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.9. Contexts and Vocabularies inconsistencies (issue controller-document#10)

_See github issue [controller-document#10](https://github.com/w3c/controller-document/issues/10)._




**Brent Zundel:** Ivan, do you have what you need to move this forward, or would group discussion help?  

**Ivan Herman:** We've made changes on DI vocabulary, there is no need for separate vocabulary for controller, that's the cleanest thing. The only thing that changes is where the formal specification pointer is. I did that, I think that addresses this issue.  
… I think it's been done.  

**Brent Zundel:** Mike Jones, this is your issue, we'd want your agreement on that.  

**Michael Jones:** I'm trying to understand why this was marked pending close, this is a twisty set of passages.  

**Ivan Herman:** I acted on Mike's requests for changes, but maybe I don't understand what Mike's commenting on.  

**Ivan Herman:** We've done the 2nd approach in [https://github.com/w3c/controller-document/issues/10#issuecomment-2122449898](https://github.com/w3c/controller-document/issues/10#issuecomment-2122449898).  

**Brent Zundel:** The first approach was overtaken by events.  

**Michael Jones:** So we removed a section from the controller document spec.  
… But we didn't remove that section?  

**Ivan Herman:** I didn't refer to any section in my comment, vocabulary description is a separate document.  

> *Michael Jones:* Because that vocabulary (and related context) is much larger than what the controller document defined, it makes sense to remove this section from the controller spec and leave the DI spec in charge.

**Michael Jones:** That's a comment from you, Ivan ^.  
… what is the "it" we're referring to?  

**Dave Longley:** I was reading over the issue, one of the things you offered Mike -- "should it be deleted" -- Ivan said that DI has been updated, referring to term in controller document. That is a little different from Ivan had written, but has been done (the 2nd suggestion you made, Mike).  

**Brent Zundel:** Yes, 2nd suggestion has been applied.  

**Michael Jones:** Ok, it would help me approve closing the issue if someone could provide a link to an old draft of DI referencing the thing that was deleted, so I can compare "this used to be there and this isn't there anymore".  
… Once that's done, I can approve closing the issue.  

**Brent Zundel:** Can DI folks point to the merged PR?  

**Dave Longley:** I followed Ivan's comment to assertion method link, which takes you to a vocabulary document, which then if you click on that, see formal definition of term, which takes you to the controller document.  

**Ivan Herman:** Yes, and previously it took you the DI specification.  

**Michael Jones:** I'm asking for a reference for an old rendering of the DI document that has the text to see what was removed.  

> *Ivan Herman:* [https://www.w3.org/standards/history/vc-data-integrity/](https://www.w3.org/standards/history/vc-data-integrity/) : history of documents.

**Ivan Herman:** We need to find at what date that change happened.  

**Brent Zundel:** We're out of time on this.  

**Manu Sporny:** I can look into the history on this.  

---

</details>

**Comment by iherman** [comment] 2024-08-14 16:30
FWIW, the PR that changed the vocabulary (which now points at the controller document) is here  https://github.com/w3c/vc-data-integrity/pull/280.

I am not familiar with all the history of changes in the DI spec proper.

**Comment by iherman** [comment] 2024-08-15 08:28
@selfissued, @brentzundel, @msporny, @dlongley

I have looked at the original issue description again. 

For the records, the two sections we are talking about are:

- In the DI spec: [§2.4 Contexts and Vocabularies](https://w3c.github.io/vc-data-integrity/#contexts-and-vocabularies)
- in the Controller spec: [§4 Contexts and Vocabularies](https://w3c.github.io/controller-document/#contexts-and-vocabularies)

Summary: @selfissued is right, there is some further work to do before we can close the issue. See below.

Reading through the sections they are, content-wise, almost identical. "Almost": the version in the controller document was "spawned" from the DI spec before some editorial improvements were made in the section in the DI spec. (An example is making a reference to the corresponding `curl` command.) But the core statement, i.e.,

> The security vocabulary terms that the JSON-LD contexts listed above resolve to are in the [https://w3id.org/security#](https://w3id.org/security) namespace.

is present in both sections and, in line of https://github.com/w3c/vc-data-integrity/pull/280, formally correct. All the rest of the sections derive from this fundamental fact. I.e., in my view, _**there is no inconsistency anymore**_.

That being said: there is duplication, and that is never good. I would think that one of the two sections must be pruned. E.g., if we decide to prune the section in the Controller Document, this would mean something like:

- making clear that the section is for those implementations that perform JSON-LD processing (essentially, keeping the first paragraph of the section);
- making a statement whereby all terms defined in this document are in the  [https://w3id.org/security#](https://w3id.org/security) namespace (like the aforementioned statement, just not saying "security vocabulary terms");
- formally refer to the DI specification for the details on context files, media types, etc.

I realize this would create a normative reference to the DI spec, but that is restricted to the JSON-LD processing, so I think that is ok. 

Alternatively, we could keep the section in the Controller spec as the core definition of the namespaces and the context files, and do a similar pruning in the DI specification instead (with a normative reference to the Controller spec). However, most of the terms defined in the [https://w3id.org/security#](https://w3id.org/security) vocabulary _are defined in the DI specification_. I.e., a formal definition for the corresponding context files in a different specification would not be appropriate, at least in my view.

Finally, a third alternative, if we are opposed to any kind of cross-references, is to keep these sections as they are. Some very minor modifications should be done on the Controller Document section; essentially, taking over the editorial improvements in the DI spec to bring them in sync. But that would mean the necessity to follow any change in the DI spec (if any) and vice versa. 

Up to the WG to decide. I am happy to come up with a PR if a decision is made in the direction.

(Procedurally, we could try to make a decision on GitHub and not to take WG telco time…)

**Comment by iherman** [comment] 2024-08-15 08:28
Per https://github.com/w3c/controller-document/issues/10#issuecomment-2290883612, my vote is to prune the Controller Document's relevant section.

**Comment by selfissued** [comment] 2024-08-15 15:22
I'm fine with either having DI delete the duplicate text and reference the text in the Controller Document spec or leaving the duplication after making the largely duplicate text identical.

I'm not OK with the Controller Document having a normative dependency on DI.

**Comment by iherman** [comment] 2024-08-15 16:03
> I'm fine with either having DI delete the duplicate text and reference the text in the Controller Document spec or leaving the duplication after making the largely duplicate text identical.
> 
> I'm not OK with the Controller Document having a normative dependency on DI.

I believe that means we have to sync up the two sections and keep them in both documents. I do not think removing the content from the DI spec is all right either...

**Comment by iherman** [comment] 2024-08-16 11:01
Having looked at the two sections in a larger document environment, things become hairy. 

The DI document contains the following subsections:

> [Contexts and Vocabularies](https://www.w3.org/TR/vc-data-integrity/#contexts-and-vocabularies)  
>  
> [2.4.1 Validating Contexts](https://www.w3.org/TR/vc-data-integrity/#validating-contexts)  
> [2.4.2 Context Injection](https://www.w3.org/TR/vc-data-integrity/#context-injection)  
> [2.4.3 Securing Data Losslessly](https://www.w3.org/TR/vc-data-integrity/#securing-data-losslessly)  
> [2.4.4 Datatypes](https://www.w3.org/TR/vc-data-integrity/#datatypes)

The Controller document contains the following sections

> [Contexts and Vocabularies](https://www.w3.org/TR/controller-document/#contexts-and-vocabularies)  
>     
> [4.1 Context Injection](https://www.w3.org/TR/controller-document/#context-injection)  
> [4.2 Datatypes](https://www.w3.org/TR/controller-document/#datatypes)  


So far, we concentrated on the “introductory” part of the main sections, which are indeed out of sync. That is easy to fix.

However, what does happen with the other subsections? In theory, because we are talking about important issues for JSON-LD implementers, the context validation and securing data should be carried over, too, and the context injection synced up if necessary. That means duplicating a fairly large portions of the specs. I believe we should really avoid doing that, it is really error-prone.

In view of earlier discussions and opinions, an alternative approach may be the following:

- In spite of what I personally think, prune the DI spec's text in favor of the Controller Document. I do not like it, but I would not formally object.
- Move the context validation, injection and lossless securing to the controller document, too, removing them from the DI spec altogether. Some editing may be necessary on the way to make the text more general.
- The Datatypes in the DI spec should only contain the `cryptosuiteString` datatype (there seems to be an error right now, it still includes `multibase`); the same section in the Controller spec should include `multibase` (just as it is now).

The added bonus of such an arrangement is that the DI spec would/could refer to the same sections as for how to deal with, for example, context injections.

The downside is that all this requires a major surgery on the documents, and this may jeopardize our publication schedule.

**Comment by iherman** [comment] 2024-08-16 11:49
Forgive me if I come up with a new alternative in every comment I make, but the issue is running around my head.

Yet another alternative may be the most radical but, possibly, the simplest. The introductory section should get a rewrite along the lines:

- we only talk about RDF based (e.g., JSON-LD) applications in general that must rely on the formal vocabulary items in the `https://w3id.org/security` namespace
- give details about the vocabulary files with different media types (the second table in the section, updated with the way it is done in the DI spec)
- mention the fact that JSON-LD applications may define their own context files to use those RDF terms. We would give the _example_ of the DI context (no normative reference here, just informative!) as well as the DID context (again, no normative reference to the DID spec) that do exactly that
- remove all subsections except for the one on datatype that remains unchanged.

And that is it. No change in the DI spec (except maybe to make it clear that the DI context includes the controller terms as well).

How does that sound?

**Comment by iherman** [comment] 2024-08-20 12:18
See #43 for a proposed solution, following https://github.com/w3c/controller-document/issues/10#issuecomment-2293364035, so resolve this issue.

**Comment by msporny** [comment] 2024-09-08 22:51
PR #92 has been raised to address this issue. This issue will be closed once PR #92 has been merged.

**Comment by msporny** [comment] 2024-09-20 12:49
PR #92 has been merged, closing.

**Closed by msporny** 2024-09-20 12:49 UTC
Labels: pr exists, normative
